### ISSUE TITLE
CWE-476: NULL Pointer Dereference - method insecure.

### ISSUE THREAD

**Issue by EvertonMelo** [bizanc/Bizanc.io.Core#36]
**Describe the bug**

file: **BalanceRepository.cs**{https://github.com/bizanc/Bizanc.io.Core/blob/master/Bizanc.io.Matching.Infra/Repository/BalanceRepository.cs#L30}

1. in line: 30 
**points.Count > 20**

2. A reference to null should never be dereferenced/accessed. Doing so will cause a NullReferenceException to be thrown.

**Additional context**
At best, such an exception will cause abrupt program termination. At worst, it could expose debugging information that would be useful to an attacker, or it could allow an attacker to bypass security measures.

### reference: 
https://wiki.sei.cmu.edu/confluence/display/c/EXP34-C.+Do+not+dereference+null+pointers

**Comment by llustosa** [comment]
Hi, thanks for posting an issue. About the bug, the null check in the line 28 is redundant. The database call, ToListAsync(), never returns null, but an empty list. Thats what happens in clean startup. The other case is the database becoming unreachable, that will throw an exception that will be catched in the miner class. Since this is in the cleanup process, if the database is unreachable the persistence will not happen too, so it will not damage the recovery data. I changed the code a bit for clarification, including the BookReposistory.cs and BlockRepository.cs that has similar methods. I'll close this issue in the pull request, but feel free to open another one if you have more questions or issues.
